New addon: avocet
WebThingsIO/addon-list pull request #1470
Opened 2022-07-25 16:22 UTC by Bleznudd

Lightweight, local and polyglot voice assistant.
Built around PicoVoice and the Respeaker 2-MIC hat.

See: [Avocet repo](https://github.com/Bleznudd/avocet)

2022-07-26 18:02 UTC, tim-hellhake commented
This is not a proper addon file.
Please have a look at the README.

2022-07-26 18:02 UTC, tim-hellhake requested changes
This is not a proper addon file.
Please have a look at the README.

2022-07-29 08:20 UTC, Bleznudd commented
My bad, I've uploaded the wrong file, which has now been overwritten and the commits squashed. 
Is it good now?

2022-08-02 08:38 UTC, Bleznudd commented
It looks like the check didn't pass because the version I specified was 0.1 and it was not in the pattern x.y.z
Let's see if it'll work out now, and if so, I suggest to clarify this requirement in the README

2022-11-10 18:22 UTC, tim-hellhake approved these changes

2022-11-10 18:23 UTC, merged

2022-11-10 18:43 UTC, tim-hellhake commented
@Bleznudd you also need to fix the version here: https://github.com/Bleznudd/avocet/blob/master/manifest.json#L18
Please open another PR after you fixed it.